spring:
  application:
    name: server
#  datasource:
#    url: jdbc:postgresql://localhost:5432/PW44SDAVI
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console

